version: '3.8'
services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./src:/var/www/html/
      - ./logs/nginx:/var/log/nginx/
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
  php:
    image: php-fpm-ml
    volumes:
      - ./src:/var/www/html/
      - ./logs/php.log:/var/log/fpm-php.www.log
    user: "1000"
  db:
    image: mysql:latest
    container_name: cgrd_mysql_db
    volumes:
      - db_data:/var/lib/mysql
      - ./db/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cgrd
      MYSQL_USER: cgrd
      MYSQL_PASSWORD: cgrd
      
volumes:
    db_data:
       driver: local
