<?php require_once 'views/layout/header.phtml'; ?>
<div class="login-form">
    <div class="form">
        <form action="/login" method="post">
            <label>
                <input type="text" name="username" placeholder="Username"/>
            </label>
            <label>
                <input type="password" name="password" placeholder="Password"/>
            </label>
            <button type="submit">
                Login
            </button>
        </form>
    </div>
</div>
<?php require_once 'views/layout/footer.phtml'; ?>